### ISSUE TITLE
motor_pwm_rate set to 0 when <> 400 and save in configurator tab pressed

### ISSUE THREAD

**Issue by DietmarM** [multiwii/baseflight-configurator#1]
Using GUI 0.63 with firmware Mar 27 2015

when e.g. motor_pwm_rate = 480 and e.g. pitch trim in configuration is changed and saved - it gets  dangerous: Motor pwm got changed to 0 - it takes 1 sec to Switch off a crazys quad (PID with 0 not working / extrem vibrations like much to large PIDs).

There is also a report about the bug in a german forum: 

http://www.kopterforum.de/topic/30718-info-baseflight-gui-l%C3%B6scht-motor-pwm-rate/

When the PWM rate is <> 400 and save is pressed in configuration tab - pwm rate gets set to 0 

Afterwards it is dificult to get it back to 400 or other simliar value.

Looks like a bug in the gui....

Thanks in advance ....

**Comment by cTn-dev** [comment]
Thanks for reporting this, it will be fixed in build 0.64.2 which will go to the chrome store today.
