### ISSUE TITLE
[gyro] box not green when accel is not avialable/disabled

### ISSUE THREAD

**Issue by trollcop** [multiwii/baseflight-configurator#6]
I had a board where isntead of MPU6050 there was a MPU3050 (gyro-only).
When connected, it works (gyro stuff moves), but the gyro box is red.

I know the MSP only provides detail about acc being available, what is the trigger in app for enabling the gyro box?

**Comment by cTn-dev** [comment]
Bit for acc in MSP_STATUS is also used to display gyro on/off, basically there is no info about gyro status in MSP, gyro box in the app is basically just a hack/fake, nothing more.

**Comment by trollcop** [comment]
ok can we hack it to be green all the time then until further notice?

if the acc is not found, all boxes are red which is kinda crap.

**Comment by cTn-dev** [comment]
Not the best solution, but sure, since the gyro status is fake anyway, i guess it doesn't matter which color it is.

**Comment by trollcop** [comment]
making it green after connection is ok.

**Comment by cTn-dev** [comment]
Got it in the dev branch, should work just fine for the time being. Anything else needs changing ?

**Comment by trollcop** [comment]
OK for now.
I've got a couple boards where MPU3050 was mounted instead of 6050, so
they're technically "gyro only".
And this was confusing users (and me :)

So this should be OK.

I'll poke you later if any more stuff needs to be looked at.

**Comment by cTn-dev** [comment]
Ok, ill get the updated build to the store in few hours.

**Comment by trollcop** [comment]
oh...
912000 baudrate thing?
I think i mentioned it on irc.
Getting  consistently shitty gang flashes at 912000 but OK at 480000 or
wahtever hte next lower level is.

 what to do?

**Comment by cTn-dev** [comment]
I can slow it down to 460800, shouldn't make too much of a difference for regular users, unfortunately i am still unable to repro the bad flash on 921600 :/

**Comment by trollcop** [comment]
ya .. I know it's annoying, maybe time for a baud rate drop box? haha..

**Comment by cTn-dev** [comment]
Only developers re-flash often, so they should be happy with the speed even at 115200
